name: Lighthouse

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: 'lighthouse-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/build-next

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@2f8dda6cf4de7d73b29853c3f29e8b2f256e5587 # v12.1.0
        with:
          configPath: ./lighthouserc.json
          uploadArtifacts: true
          temporaryPublicStorage: true
